Found 'btvinfo' with frequency 176464
Delete 'btvinfo' succeeded
NOT Found 'btvinfo'
Found 'sassone' with frequency 52340
Delete 'sassone' succeeded
NOT Found 'sassone'
Add 'booming' succeeded
Found 'booming' with frequency 123456
Autocomplete for 'boo': [ books: 347710184  bookmark: 27665146  booking: 23522206  ]
Delete 'booming' succeeded
Autocomplete for 'boo': [ books: 347710184  bookmark: 27665146  booking: 23522206  ]
Found 'broeck' with frequency 39549
Autocomplete for 'bro': [ broadband: 26476075  brothers: 22101521  broad: 21370126  ]
Autocomplete for 'nec': [ necessary: 72604405  necessarily: 15867816  necessitates: 370877  ]